### ISSUE TITLE
License, and GitHub discoverability features

### ISSUE THREAD

**Issue by SirLich** [gdquest-demos/godot-4-3D-Characters#2]
Thanks as always for providing these epic resources!

The repository is lacking some GitHub-specific features, such as a description, website, and labels. These are surprisingly important for organic discovery (assuming the goal is to get lots of people using the assets :P)

On top of that, the license isn't clear to me. The readme says these are 'open  source', so I assume the license is permissive, but it would be awesome if you would clarify with a license file. Even permissive licenses like MIT or CC0 have some subtle differences/restrictions. 

I actually checked your website and I *think* it might be this one? https://creativecommons.org/licenses/by/4.0/, which requires attribution (that's fine, but it's just good to be clear about these things).

**Comment by NathanLovato** [comment]
Thanks for the heads up. I added these yesterday, the license is MIT for everything right now. GitHub doesn't really support dual licenses, I was looking to do MIT/CC0 for code and art respectively but I think we'll just use MIT from there on for simplicity.
