### ISSUE TITLE
[Gobot] [Import Issue] Models will not properly import if the files are not in a res://models/ folder

### ISSUE THREAD

**Issue by Cole-Allen** [gdquest-demos/godot-4-3D-Characters#3]
Just wanted to note that importing only seems to work when you drag a character model folder to res://models/{your model file here}. Failing to do this messes up the model
![image](https://github.com/gdquest-demos/3D-Characters-Repository/assets/56735362/f21d31c7-7450-40ab-a21e-61a1245b0524)

**Comment by NathanLovato** [comment]
That's normal, it's true for all files in Godot, they're path-sensitive. You have to first copy to your project using the same path, then move or rename folders from within the Godot editor.
